### ISSUE TITLE
REVISION DE SINTAXIS

### ISSUE THREAD

**Issue by eychamba** [MASTERPC-CIA/bill_nomina#3]
Angel hay un error de sintaxis en el modulo de nominas al comprobar existencia de fechas: 
if (!empty($this->fecha_ini != '')) {

y además cuando hacemos uso del modelo "grocery_join_model" es necesario en el nombre de la columna de cualquiera de las tablas anteponer el alias o el nombre completo de la tabla, ejemplo, esta dando un error al consultar  'estado' de la factura, ya que esa columna tambien existe en otras relacionadas, la forma correcta seria 'billing_facturaventa.estado'
Corregir eso y hacer un push a bill_nomina.

**Comment by eychamba** [comment]
Revisar con Angel si continúa ese error en la sintaxis: if (!empty($this->fecha_ini != '')) { , esa línea está mal escrita.

**Comment by viche1991angel** [comment]
Corregido el error de la sintaxis

**Comment by angelvcuenca** [comment]
Ya se encuentra solucioando el problema del sintaxis, el bug esta al modulo de reportes no en el nomina
